### ISSUE TITLE
register vendered six into global namespace may break stuff

### ISSUE THREAD

**Issue by davidlatwe** [mottosso/allzpark#137]
**This is an edge case I suppose**, strange `ModuleNotFoundError` raise when something requires `six.moves`.

In my case it was a [python rez-package](https://github.com/davidlatwe/rez-python-venv) that uses `pythonfinder` module to list out system python and provide venv to use. And the `pythonfinder` module has [it's own `six.moves` registered](https://github.com/sarugaku/pythonfinder/blob/dfac150ffeaccbcb3c2867c5429b38b568d85a8d/src/pythonfinder/utils.py#L21-L29) and the `ModuleNotFoundError` raised from there due to the module `six` is already imported as global one in Allzpark launch-time and it doesn't have `.moves`.

https://github.com/mottosso/allzpark/blob/43eb8e0d8d89449ab1accae9653687fc51dc37a6/allzpark/cli.py#L192-L198

**Although following log message is not generated from the current master branch of Allzpark but my forked one, but the root cause is the same.**

<details>
<summary>Full error log</summary>

```
$ rez-park
==============================
 allzpark (2.0.48)
==============================
- Loading Rez.. (2.88.1-m) - ok 0.00
- Loading Qt.. (PySide2 - 5.15.2) - ok 0.88
- Loading allzpark.. (2.0.48) - ok 0.10
- Loading allzparkconfig.. ok - 0.00
- Loading application parent environment.. ok - 0.00
- Loading preferences.. (C:/Users/davidlatwe.lai/AppData/Roaming/Allzpark/preferences.ini) ok - 0.01
------------------------------
- Loading themes.. ok - 0.02
- Loading environment plugin.. no plugin - ok
- Resolved contexts.. ok 0.11s
Traceback (most recent call last):
  File "c:\users\davidlatwe.lai\pipeline\allzpark\allzpark\control.py", line 970, in on_apps_not_found
    raise error
  File "c:\users\davidlatwe.lai\pipeline\allzpark\allzpark\util.py", line 165, in run
    result = self.target(*self.args, **self.kwargs)
  File "c:\users\davidlatwe.lai\pipeline\allzpark\allzpark\control.py", line 1240, in _list_apps
    for tool_alias, tool_entry in suite.get_tools().items():
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\suite.py", line 307, in get_tools
    self._update_tools()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\suite.py", line 717, in _update_tools
    context = self.context(context_name)
  File "c:\users\davidlatwe.lai\pipeline\sweet\src\sweet\_rezapi.py", line 50, in context
    context = ResolvedContext(self._requests[name])
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\resolved_context.py", line 308, in __init__
    resolver.solve()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\memcached.py", line 267, in wrapper
    return func(*nargs, **kwargs)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\resolver.py", line 119, in solve
    solver = self._solve()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\resolver.py", line 404, in _solve
    solver.solve()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 2082, in solve
    self.solve_step()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 2162, in solve_step
    new_phase = phase.solve()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 1368, in solve
    scope = _PackageScope(req, solver=self.solver)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 972, in __init__
    package_request.name, package_request.range)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 2338, in _get_variant_slice
    package_name=package_name, range_=range_)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 941, in get_variant_slice
    variant_list = _PackageVariantList(package_name, self.solver)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 470, in __init__
    paths=self.solver.package_paths):
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\packages.py", line 558, in iter_packages
    for package_resource in repo.iter_packages(family_resource):
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\memcached.py", line 262, in wrapper
    for result in func(*nargs, **kwargs):
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rezplugins\package_repository\filesystem.py", line 560, in iter_packages
    for package in self.get_packages(package_family_resource):
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\backport\lru_cache.py", line 74, in wrapper
    result = user_function(*args, **kwds)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rezplugins\package_repository\filesystem.py", line 1130, in _get_packages
    return [x for x in package_family_resource.iter_packages()]
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rezplugins\package_repository\filesystem.py", line 1130, in <listcomp>
    return [x for x in package_family_resource.iter_packages()]
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rezplugins\package_repository\filesystem.py", line 313, in iter_packages
    if config.allow_unversioned_packages and not self.versions:
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\data_utils.py", line 245, in __get__
    result = self.func(instance)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\data_utils.py", line 657, in getter
    if key not in (self._data or {}):
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\data_utils.py", line 245, in __get__
    result = self.func(instance)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\resources.py", line 97, in _data
    data = self._load()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rezplugins\package_repository\filesystem.py", line 337, in _load
    disable_memcache=self._repository.disable_memcache
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 141, in load_from_file
    update_data_callback=update_data_callback)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\memcached.py", line 383, in wrapper
    result = func(*nargs, **kwargs)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 160, in _load_from_file
    return _load_file(filepath, format_, update_data_callback)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 174, in _load_file
    result = load_func(f, filepath=filepath)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 231, in load_py
    return _load_py(stream, filepath=filepath)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 269, in _load_py
    result = process_python_objects(result, filepath=filepath)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 393, in process_python_objects
    data = _process(data)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 311, in _process
    value[k] = _process(v)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 345, in _process
    value_ = fn()
  File "c:\users\davidlatwe.lai\rez\packages\combined\python.py", line 11, in versions
    from pythonfinder import Finder
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\pythonfinder\__init__.py", line 10, in <module>
    from .models import SystemPath, WindowsFinder
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\pythonfinder\models\__init__.py", line 11, in <module>
    from ..utils import KNOWN_EXTS, unnest
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\pythonfinder\utils.py", line 28, in <module>
    from six.moves import Iterable  # type: ignore  # noqa  # isort:skip
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'six.moves'
```

</details>

I will resolve this on my fork for now, by removing `six` from vendor because the branch I am working on is not supporting Python 2 and like I said above, this should be an edge case. Just reporting here for the record.

**Comment by mottosso** [comment]
> due to the module six is already imported as global one in Allzpark launch-time

Where does this happen? :O Six should be explicitly imported into the local space, using the vendored copy, and not pollute `sys.modules` with `"six"`, but rather `"allzpark.vendor.six"` which should not interfere with other references to `six`.

Like this one:

https://github.com/mottosso/allzpark/blob/43eb8e0d8d89449ab1accae9653687fc51dc37a6/allzpark/model.py#L45

Based on the log, this looks like a problem with bleeding-rez, which maybe does import into the global space? :S

**Comment by davidlatwe** [comment]
Hmmm, not sure.. But I did test with adding `import six.moves` before these line https://github.com/mottosso/allzpark/blob/43eb8e0d8d89449ab1accae9653687fc51dc37a6/allzpark/cli.py#L192-L198

and the problem is gone. And adding the line *after* those bring back the error.

**Comment by davidlatwe** [comment]
To be more precise these makes the difference

No error, works fine.
```python
    # In allzpark.cli Line 194
    # Provide for vendor dependencies
    import six
    sys.modules["Qt"] = Qt
    sys.modules["six"] = six
```

Error raised.
```python
    # In allzpark.cli Line 194
    # Provide for vendor dependencies
    sys.modules["Qt"] = Qt
    sys.modules["six"] = six
    import six
```

**Comment by mottosso** [comment]
Oooh yes you are right, darn it. Yes, you're right.

The problem one or more of the vendored packages requires six, but does *not* use the relative import syntax. This is a workaround for that.. That's a bummer.

Your first solution assumes `six` is available outside of Allzpark, if that was the case then the below workaround would not be necessary. We could make `six` a dependency of Allzpark, it wouldn't be the end of the world.. Except, in this particular case it looks like the versions of `six` are different, so we'd maybe end up with an impossible version requirement?

That said, the latest version should likely work with both of them.

> Simply adding sys.modules["six.moves"] = six.moves after the line sys.modules["six"] = six also solve the problem.

Mm, but that still assumes `six` is available on PYTHONPATH.

We could do that.

1. Take `six` out of `vendor/`
2. Make `six` a dependency via `setup.py`

That would be a proper way to solve it. And should probably have been the case from the start, since those darn vendored libraries (can't remember which one, maybe even Rez?) reach into the global path for vendored libraries.. :(

**Comment by davidlatwe** [comment]
Nice, then I'll make a PR for it, which will take `six` out of vendor 🎉
