### ISSUE TITLE
Problem while installing. Breaks at rez bind --quiickstart | windows 10 64 bit

### ISSUE THREAD

**Issue by sajeelshukla** [mottosso/allzpark#152]
Hi like the title says it gets stuck at rez bind --quickstart. 
Not sure what to do. Here's the log.
 
`C:\WINDOWS\system32>python -m pip install allzpark --upgrade
Requirement already satisfied: allzpark in c:\users\titanws\appdata\local\programs\python\python311\lib\site-packages (1.2.84)
Collecting allzpark
  Using cached allzpark-1.3.129-py2.py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: bleeding-rez>=2.38.2 in c:\users\titanws\appdata\local\programs\python\python311\lib\site-packages (from allzpark) (2.40.5)
Requirement already satisfied: allzparkdemo>=1 in c:\users\titanws\appdata\local\programs\python\python311\lib\site-packages (from allzpark) (1.0.23)
INFO: pip is looking at multiple versions of allzpark to determine which version is compatible with other requirements. This could take a while.
  Using cached allzpark-1.3.67-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.3.41-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.3.31-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.3.28-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.3.5-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.3.3-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.3.0-py2.py3-none-any.whl.metadata (1.2 kB)
INFO: pip is still looking at multiple versions of allzpark to determine which version is compatible with other requirements. This could take a while.
  Using cached allzpark-1.2.208-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.183-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.179-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.177-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.164-py2.py3-none-any.whl.metadata (1.2 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached allzpark-1.2.162-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.148-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.147-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.145-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.141-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.140-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.130-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.128-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.106-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.103-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.102-py2.py3-none-any.whl.metadata (1.2 kB)
  Using cached allzpark-1.2.92-py2.py3-none-any.whl.metadata (1.2 kB)

C:\WINDOWS\system32>rez bind --quickstart
Traceback (most recent call last):
  File "C:\Users\TitanWs\AppData\Local\Programs\Python\Python311\Lib\logging\config.py", line 149, in _install_handlers
    klass = eval(klass, vars(logging))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'rez' is not defined. Did you mean: 're'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TitanWs\AppData\Local\Programs\Python\Python311\Lib\logging\config.py", line 104, in _resolve
    found = getattr(found, n)
            ^^^^^^^^^^^^^^^^^
AttributeError: module 'rez.utils' has no attribute 'colorize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\TitanWs\AppData\Local\Programs\Python\Python311\Scripts\rez.exe\__main__.py", line 4, in <module>
  File "C:\Users\TitanWs\AppData\Local\Programs\Python\Python311\Lib\site-packages\rez\__init__.py", line 20, in <module>
    logging.config.fileConfig(logging_conf_file, disable_existing_loggers=False)
  File "C:\Users\TitanWs\AppData\Local\Programs\Python\Python311\Lib\logging\config.py", line 90, in fileConfig
    handlers = _install_handlers(cp, formatters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TitanWs\AppData\Local\Programs\Python\Python311\Lib\logging\config.py", line 151, in _install_handlers
    klass = _resolve(klass)
            ^^^^^^^^^^^^^^^
  File "C:\Users\TitanWs\AppData\Local\Programs\Python\Python311\Lib\logging\config.py", line 106, in _resolve
    __import__(used)
  File "C:\Users\TitanWs\AppData\Local\Programs\Python\Python311\Lib\site-packages\rez\utils\colorize.py", line 5, in <module>
    from rez.config import config
  File "C:\Users\TitanWs\AppData\Local\Programs\Python\Python311\Lib\site-packages\rez\config.py", line 2, in <module>
    from rez.utils.data_utils import AttrDictWrapper, RO_AttrDictWrapper, \
  File "C:\Users\TitanWs\AppData\Local\Programs\Python\Python311\Lib\site-packages\rez\utils\data_utils.py", line 7, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (C:\Users\TitanWs\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py)

C:\WINDOWS\system32>allzpark --demo --clean`

**Comment by mottosso** [comment]
Try one of the tested Python versions for this, 3.5 to 3.7

**Comment by sajeelshukla** [comment]
Thank you will try 3.7 :)

**Comment by sajeelshukla** [comment]
hi @mottosso 
So i ran into a problem. The pipeline i am creating is using mysql database and downgrading python to 3.7 i am unable to use my exisiting scritps that use mysql as it says missing module msqldb i scowered the net but it seems it just does not woth with 3.7 on windows. 

Is there some other way where i can fix the install problem with my current setup ?

**Comment by mottosso** [comment]
There's no need to use the same Python with allzpark as you do anywhere else, put a sandboxed Python install in a folder near allzpark and use it exclusively to launch and use allzpark.

**Comment by sajeelshukla** [comment]
Hi Mottosso, sorry for such a late reply i had got busy with work and life so had to put this install and setup on hold. How exactly do i do this sandboxed Python thing?

I have tried following things
1: got python zip (portable ) extracted in c:\allzprak and run python.exe -m pip install .... commands
it was not finding pip. so i ran get-pip.py script that i found online, but it would find site-packages from python 3.13 as main Python verion 

2: also tried to do same with winpython but again similar set of problems it wont find some thing and when i do pip install it would read in python3.13.

So the question is how to run this all in sandbox  and have allzpark configured correctly. 

P.s i also tried to manually copy allzprak from site-packages of python 3.13 to the 3.7 zip folder but when i run 
allzpark --demo it goes looking in python313 folder where it origanally downloaded and installed. 

One last thing allzpark --demo --clean does not work says unrecognized arguments: --clean
